import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ThemeTogglerProvider } from "@/contexts/theme-toggler-context";

const rubik = Rubik({
  variable: "--font-rubik-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <ThemeTogglerProvider>{children}</ThemeTogglerProvider>
      </body>
    </html>
  );
}
