import "./globals.css";

import type { Metadata } from "next";
import { Cactus_Classical_Serif, Rubik } from "next/font/google";

const rubik = Rubik({
  variable: "--font-rubik-serif",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const cactusClassical = Cactus_Classical_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(rubik.className, cactusClassical.className)}>
        {children}
      </body>
    </html>
  );
}
